export const synonyms = {
  sun: 'SolarPanel',
  wind: 'WindTurbine',
  always: 'Generator',
  smallGenerator: 'Generator',
  smallWindTurbine: 'WindTurbine',
  smallSolarPanel: 'SolarPanel',
  mediumGenerator: 'Generator',
  mediumShredder: 'Shredder',
  mediumWindTurbine: 'WindTurbine',
  mediumSolarPanel: 'SolarPanel',
  largeWindTurbine: 'WindTurbine',
  largeSolarPanel: 'SolarPanel',
  xlargeWindTurbine: 'WindTurbine',
  fieldShelter: 'Shelter',
  shelter: 'Shelter',
  chemistryLab: 'ChemistryLab',
  atmosphericCondenser: 'AtmosphericCondenser',
  smeltingFurnace: 'SmeltingFurnace',
  rtg: 'Generator',
  qtRtg: 'Generator',
  smallBattery: 'Battery',
  mediumBattery: 'Battery',
};

export const tier = {
  1: 'Small',
  2: 'Medium',
  3: 'Large',
  4: 'ExtraLarge',
};
